# Generated by Django 5.2.5 on 2025-08-22 04:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_custom_user_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('purchase_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchase_order_name', models.CharField(verbose_name='purchase_order_name')),
                ('purchse_status', models.CharField(choices=[('SUCESS', 'Sucess'), ('PENDNG', 'Pending'), ('FAILURE', 'Failure'), ('INITIATED', 'Initiated')], default='INITIATED')),
                ('pidx', models.CharField(editable=False, verbose_name='pidx')),
                ('khalti_status', models.CharField(editable=False, verbose_name='Status From Khalti ')),
                ('khalti_transaction_id', models.CharField(editable=False, verbose_name='Khati Transation ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
