# Generated by Django 5.2.5 on 2025-08-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='purchase_amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
