# Generated by Django 5.2.5 on 2025-08-22 04:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_payment_purchase_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='initiated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='purchase_amount',
            field=models.FloatField(null=True),
        ),
    ]
