# Generated by Django 5.2.5 on 2025-08-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_payment_initiated_at_payment_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
