# Generated by Django 5.2.5 on 2025-08-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_custom_user_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='purchse_status',
            field=models.CharField(choices=[('SUCESS', 'Sucess'), ('PENDNG', 'Pending'), ('FAILURE', 'Failure'), ('INITIATED', 'Initiated'), ('REFUNDED', 'Refunded')], default='INITIATED'),
        ),
    ]
